//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateBook.DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DateBookDbEntities : DbContext
    {
        public DateBookDbEntities()
            : base("name=DateBookDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
    
        public virtual int sp_InsertNote(string tittle, string description, Nullable<System.DateTime> finishDate, Nullable<decimal> paymentAmount)
        {
            var tittleParameter = tittle != null ?
                new ObjectParameter("tittle", tittle) :
                new ObjectParameter("tittle", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var finishDateParameter = finishDate.HasValue ?
                new ObjectParameter("finishDate", finishDate) :
                new ObjectParameter("finishDate", typeof(System.DateTime));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("paymentAmount", paymentAmount) :
                new ObjectParameter("paymentAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNote", tittleParameter, descriptionParameter, finishDateParameter, paymentAmountParameter);
        }
    
        public virtual ObjectResult<sp_SelectNotes_Result> sp_SelectNotes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectNotes_Result>("sp_SelectNotes");
        }
    }
}
